package edu.jhuapl.sbmt.query.filter.ui.table;

public enum FilterColumnLookup
{
	FILTER_ENABLED,
	FILTER_NAME,
	FILTER_TYPE,
	FILTER_LOW,
	FILTER_HIGH,
	FILTER_RANGE,
	FILTER_UNITS,
	FILTER_START_DATE,
	FILTER_START_TIME,
	FILTER_END_DATE,
	FILTER_END_TIME
}
